name: Playwright E2E Tests

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps

      - name: Run quality checks (lint, format, tsc)
        run: |
          npm run format:check
          npm run lint
          npm run tsc

      - name: Run Playwright tests
        run: npm run test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results (traces, screenshots)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
